### Missing instance ('inst')
POST http://localhost/phpstorm/api/gifs.php
Content-Type: application/x-www-form-urlencoded

username=defvs&url=https://media.giphy.com/media/YTPp28PKl42ootr8sR/giphy.mp4

###

### "Good" POST request
POST http://localhost/phpstorm/api/gifs.php
Content-Type: application/x-www-form-urlencoded

username=defvs&url=https://media.giphy.com/media/YTPp28PKl42ootr8sR/giphy.mp4&inst=gifs

###

### "Good" GET request
GET http://localhost/phpstorm/api/gifs.php?inst=gifs
###