### Test requests for new_instance.php

### "No data" --> 400
POST http://localhost/phpstorm/admin/new_instance.php
Content-Type: application/x-www-form-urlencoded


###

### Good request --> 201 Namespace created at [namespace]
POST http://localhost/phpstorm/admin/new_instance.php
Content-Type: application/x-www-form-urlencoded

username=defvs
###